### ISSUE TITLE
You don't have permission to access / on this server

### ISSUE THREAD

**Issue by vitorbrandao** [maglnet/docker-zf2#1]
Getting the following message after starting the container and accessing `http://localhost:8080`

```
Forbidden

You don't have permission to access / on this server.

Apache/2.4.7 (Ubuntu) Server at localhost Port 8080
```

Followed instructions as described in https://github.com/maglnet/docker-zf2#example-with-zf2-skeleton-application, without MySQL. Can't see anything in the Apache logs.

Using Docker beta Version 1.11.1-beta13.1 (build: 8193).

Can you help?

**Comment by maglnet** [comment]
Hi, sorry for the late response.
Do you have an `index.php` within your `public` folder?
What if you try to access `http://localhost:8080/index.php` ?

**Comment by lifetoss** [comment]
I too have the same issue, could you help me to figure out this issue.
when I run my docker container I get this issue.

 Forbidden
You don't have permission to access / on this server.
Apache/2.4.25 (Debian) Server at localhost Port 9090

**Comment by lifetoss** [comment]
I too have the same issue, could you help me to figure out this issue.
when I run my docker container I get this issue.

```
Forbidden
You don't have permission to access / on this server.
Apache/2.4.25 (Debian) Server at localhost Port 9090
```

**Comment by maglnet** [comment]
Well, same question as above ;)
Please provide some additional info, so it is somehow possible to help.
Best regards

**Comment by greg-marra** [comment]
I'm also having this issue. I'm trying to use WSL and docker for windows. It looks like no matter what I try, docroot is mounted into the container. I tested by creating docroot and an index.html to verify the web server is working.

fin sysinfo:

[~/projects/NYSCA] $ fin sysinfo
███  OS
WSL Ubuntu 18.04
Linux W8B5VW52 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

███  ENVIRONMENT
MODE : Docker Desktop

███  FIN
fin version: 1.85.1

███  DOCKER COMPOSE
EXPECTED VERSION: 1.23.2
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

███  DOCKER
EXPECTED VERSION: 18.09.2

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:11:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

███  DOCKSAL: PROJECTS
project             STATUS                    virtual host                                    project root
nysca               Up 10 minutes (healthy)   nysca.docksal,*.nysca.docksal,nysca.docksal.*   /home/gmarra/projects/NYSCA

███  DOCKSAL: VIRTUAL HOSTS
*.nysca.docksal
nysca.docksal.*
nysca.docksal

███  DOCKSAL: DNS
curl: (6) Could not resolve host: dns-test.docksal
ERROR: Requesting http://dns-test.docksal failed!

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                    PORTS                                                       NAMES
2cd6da04efb2        docksal/ssh-agent:1.2     "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes (healthy)                                                               docksal-ssh-agent
949fe6cdf6ae        docksal/dns:1.1           "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes (healthy)   192.168.64.100:53->53/udp                                   docksal-dns
93fb95255384        docksal/vhost-proxy:1.5   "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes (healthy)   192.168.64.100:8080->80/tcp, 192.168.64.100:8443->443/tcp   docksal-vhost-proxy
3c686309b65c        docksal/apache:2.4-2.3    "httpd-foreground"       2 hours ago         Up 10 minutes (healthy)   80/tcp, 443/tcp                                             nysca_web_1
6824e4a5233d        docksal/cli:2.1-php7.1    "/opt/startup.sh sup…"   2 hours ago         Up 10 minutes (healthy)   22/tcp, 3000/tcp, 9000/tcp                                  nysca_cli_1
405edc2d8d6d        docksal/mysql:5.6-1.4     "docker-entrypoint.s…"   2 hours ago         Up 10 minutes (healthy)   0.0.0.0:32774->3306/tcp                                     nysca_db_1

███  DOCKER: NETWORKS
NETWORK ID          NAME                    DRIVER              SCOPE
a72e3c656cfa        _default                bridge              local
83635e50a581        bridge                  bridge              local
ba3ec082ddc5        host                    host                local
92fabd6632da        none                    null                local
7048429530c8        nygearupnygov_default   bridge              local
59ad022bf4de        nysca_default           bridge              local

███  DOCKER DESKTOP
EXPECTED VERSION: 2.0.0.3

Docker Desktop
Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
OS Name: Windows 10 Enterprise
Windows Edition: Enterprise
Windows Build Number: 17763

███  HDD Usage
Caption  FreeSpace      Size
C:       90376826880    254859341824
D:       1000020795392  1000202039296
E:
O:
V:

fun config show:

[~/projects/NYSCA] $ fin config show
---------------------
COMPOSE_PROJECT_NAME_SAFE: nysca
COMPOSE_FILE:
/home/gmarra/.docksal/stacks/volumes-bind.yml
/home/gmarra/.docksal/stacks/stack-default.yml
/home/gmarra/projects/NYSCA/.docksal/docksal.yml
ENV_FILE:
/home/gmarra/projects/NYSCA/.docksal/docksal.env

PROJECT_ROOT: /home/gmarra/projects/NYSCA
DOCROOT: docroot
VIRTUAL_HOST: nysca.docksal
VIRTUAL_HOST_ALIASES: *.nysca.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32774

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: greg.marra@its.ny.gov
      GIT_USER_NAME: Greg Marra
      HOST_GID: '1000'
      HOST_UID: '1000'
      PHP_IDE_CONFIG: serverName=nysca.docksal
      SECRET_ACAPI_EMAIL: null
      SECRET_ACAPI_KEY: null
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: nysca.docksal
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:2.1-php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "false"
      io.docksal.project-root: /home/gmarra/projects/NYSCA
      io.docksal.virtual-host: nysca.docksal,*.nysca.docksal,nysca.docksal.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/gmarra/projects/NYSCA
      o: bind
      type: none

---------------------

**Comment by maglnet** [comment]
Hi,

where is your folder located, that you want to mount into the container.

I know from docker for Windows that it is only possible to mount folders that are inside of your windows home folder.

So something like this won't work:
C:\Projects\zf2-app 

But this will work:
C:\Users\<yourusername>\Projects\zf2-app

May this be the problem?

Best regards
Matthias

**Comment by greg-marra** [comment]
Hey Matthias,

I posted my issue in the wrong project, but I am in the below directory:

C:\Users\<User Name>\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs

**Comment by edwin66627** [comment]
> 
> Hi, where is your folder located, that you want to mount into the container. I know from docker for Windows that it is only possible to mount folders that are inside of your windows home folder. So something like this won't work: C:\Projects\zf2-app But this will work: C:\Users\<yourusername>\Projects\zf2-app May this be the problem? Best regards Matthias

oohh, thank you so much, that simple mistake was killing me
